"""Add jobs and webhooks tables

Revision ID: c43fb7669c77
Revises: 2ca2dc07bf98
Create Date: 2026-02-26 17:29:07.853744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43fb7669c77'
down_revision: Union[str, None] = '2ca2dc07bf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
